arbitrum:mainnet:
  CryptoFromPoolsRateArbitrumWAgg-1: 
    name: CryptoFromPoolsRateArbitrumWAgg
    date: 2024-09-11
    PlaceHolder:
      address: 0xa27d6c7c66e3850ca213379ddcebd4382fc93c81
      explorer: https://arbiscan.io/address/0xa27d6c7c66e3850ca213379ddcebd4382fc93c81#readContract
      vyper: 0.4.0